[tox]
isolated_build = true
envlist = py38, py39, format, lint, build

[gh-actions]
python =
    3.9: py39, format, lint, build
    3.8: py38

[flake8]
max-line-length = 79
max-complexity = 18
ignore = D102, D107, E203, E266, W503
docstring-convention = google
per-file-ignores = __init__.py:D104,F401
exclude = .git,
    __pycache__,
    setup.py,
    build,
    dist,
    docs,
    releases,
    .venv,
    .tox,
    .mypy_cache,
    .pytest_cache,
    .vscode,
    .github,
    # By default test codes will be linted.
    # tests

[mypy]
ignore_missing_imports = True

[coverage:run]
# uncomment the following to omit files during running
#omit =
[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    if self.debug:
    if settings.DEBUG
    raise AssertionError
    raise NotImplementedError
    if 0:
    if __name__ == .__main__.:
    def main

[testenv]
allowlist_externals = pytest
extras =
    test
passenv = *
setenv =
    PYTHONPATH = {toxinidir}
    PYTHONWARNINGS = ignore
commands =
    pytest \
        --cov=biobank \
        --cov-branch \
        --cov-report=xml \
        --cov-report=term-missing \
        tests

[testenv:format]
allowlist_externals =
    autoflake
    isort
    black
extras =
    test
commands =
    autoflake \
        --in-place \
        --recursive \
        --remove-unused-variables \
        --remove-all-unused-imports \
        biobank
    isort biobank
    black biobank tests

[testenv:lint]
deps = types-PyYAML
allowlist_externals =
    flake8
    mypy
extras =
    test
commands =
    flake8 biobank tests
    mypy biobank tests

[testenv:build]
allowlist_externals =
    poetry
    mkdocs
    twine
extras =
    doc
    dev
commands =
    poetry build
    mkdocs build
    twine check dist/*
